INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_SYNCSIGNALMOD SyncSignalMod)

FIND_PATH(
    SYNCSIGNALMOD_INCLUDE_DIRS
    NAMES SyncSignalMod/api.h
    HINTS $ENV{SYNCSIGNALMOD_DIR}/include
        ${PC_SYNCSIGNALMOD_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    SYNCSIGNALMOD_LIBRARIES
    NAMES gnuradio-SyncSignalMod
    HINTS $ENV{SYNCSIGNALMOD_DIR}/lib
        ${PC_SYNCSIGNALMOD_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SYNCSIGNALMOD DEFAULT_MSG SYNCSIGNALMOD_LIBRARIES SYNCSIGNALMOD_INCLUDE_DIRS)
MARK_AS_ADVANCED(SYNCSIGNALMOD_LIBRARIES SYNCSIGNALMOD_INCLUDE_DIRS)

